# -*- coding: utf-8 -*-
"""sentence to table

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VXxVIUkMcZD44XnZ4pM1zC-fXhGHW25f
"""

!pip install transformers torch pandas
from transformers import pipeline
import pandas as pd

#Load sentiment analysis model is used to seperate pros ans cons

sentiment = pipeline("sentiment-analysis")

#Sample product review (you can change only this text later)

reviews = """The laptop starts quickly and works smoothly for daily tasks.

The screen quality is clear and good for watching videos.

Battery backup is average and needs charging often.

The fan makes noise when many apps are running.

Overall, it is a good laptop for students but not for gaming.
"""
#Split review into sentences
#sentences is a variable that stores the splitted reviews
sentences = reviews.split(".")

pros = []

cons = []

for s in sentences:

    s = s.strip()

    if s == "":

        continue

    result = sentiment(s)[0]

    if result["label"] == "POSITIVE":

        pros.append(s)

    elif result["label"] == "NEGATIVE":

         cons.append(s)

pros = pros[:2]

cons = cons[:2]


#Create table

df = pd.DataFrame({

    "Pros": pros,

    "Cons": cons

})

df