# -*- coding: utf-8 -*-
"""text generation ai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kCgOANnS47hfbIXAWNKjD1-m8nzbNXLt
"""

!pip install transformers torch

from transformers import pipeline
#Load text generation model(Gen Ai)
#transformer torch only for normal sentences
#!to run code as sytem command
generator=pipeline(
"text-generation",
model="gpt2"
)
#Input prompt
prompt="Artificial intelligence in finance will"
#generate text
result=generator (prompt, max_length=50, num_return_sequences=1)
print("AI generated text:")
print(result[0]['generated_text'])